import express from "express";
const router = express.Router();
import {
  createUser,
  allUsers,
  issuedBooksToUser,
} from "../Controller/UserController.js";

import {
  createBook,
  getBooksByQuery,
  allBooks,
  getBooksStatus,
  rentGeneratedByBook,
  getBooksIssuedInRange,
} from "../Controller/bookController.js";

import { bookIssue, bookReturn } from "../Controller/trancationsController.js";

// User Api

// To createUser
router.post("/createUser", createUser);

// To get all user
router.get("/allUsers", allUsers);

// List of books issued to that person
router.get("/user/:userId", issuedBooksToUser);

// Book Api

// To createBook
router.post("/createBook", createBook);

// To get list of books
router.get("/allBooks", allBooks);

// To get books by query
router.get("/getBooks", getBooksByQuery);

// // To get booksStatus
router.get("/getBooksStatus/:bookname", getBooksStatus);

// Total rent generated by that book.
router.get("/totalRent/:bookname", rentGeneratedByBook);

// To get book in that Date range
router.get("/books/issued-in-range", getBooksIssuedInRange);

// Transaction api

// When book it is issued
router.post("/transaction/issue", bookIssue);

// When book it is return
router.put("/transaction/return", bookReturn);

export default router;
